import { cookies } from 'next/headers';
import { Footer, Header, CategoriesNavbar } from '@/components';
import './globals.css';

export const metadata = {
  title: 'Medica+',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  const cookiesStore = cookies();
  const user = JSON.parse(cookiesStore.get('user')?.value) || null;

  return (
    <html lang='en'>
      <body>
        <Header user={user} />
        {user && <CategoriesNavbar />}

        {children}
        <Footer />
      </body>
    </html>
  );
}
