import { Footer, Header } from '@/components';

import './globals.css';

export const metadata = {
  title: 'Medica+',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <Header />

        {children}
        <Footer />
      </body>
    </html>
  );
}
