import { Footer, Header, RedLine, Slider } from '@/components';
import { CategoriesList } from '@/sections';
import './globals.css';

export const metadata = {
  title: 'Medica+',
  description: 'Generated by create next app',
};
const categoriesList = [
  { id: 1, title: 'Medical' },
  { id: 1, title: 'Medical' },
  { id: 1, title: 'Medical' },
  { id: 1, title: 'Medical' },
  { id: 1, title: 'Medical' },
  { id: 1, title: 'Medical' },
];
export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <Header />
        <RedLine />
        <Slider/>
        <CategoriesList categoriesList={categoriesList}/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
