import { Lato } from 'next/font/google';
import { CssBaseline } from '@mui/material';
import { Footer, Header, CategoriesNavbar } from '@/components';
import StateProvider from '@/components/Provider';
import './globals.css';

const lato = Lato({
  subsets: ['latin'],
  weight: ['100', '300', '400', '700'],
});
export const metadata = {
  title: 'Medica+',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html
      lang='en'
      className={lato.className}>
      <body>
        <CssBaseline />
        <StateProvider>
          <Header />
          <CategoriesNavbar />
        </StateProvider>

        {children}
        <Footer />
      </body>
    </html>
  );
}
